#ifndef CONFIG_H
#define CONFIG_H

#define CROSOS_TOTAL_INTERRUPTS 512

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define CROSOS_HEAP_SIZE_BYTES 104857600 // 100MB heap size
#define CROSOS_HEAP_BLOCK_SIZE 4096
#define CROSOS_HEAP_ADDRESS 0x01000000
#define CROSOS_HEAP_TABLE_ADDRESS 0x00007E00

#define CROSOS_SECTOR_SIZE 512

#define CROSOS_MAX_FILESYSTEMS 12
#define CROSOS_MAX_FILE_DESCRIPTORS 512

#define CROSOS_MAX_PATH 108

#define CROSOS_TOTAL_GDT_SEGMENTS 6

#define CROSOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define CROSOS_USER_PROGRAM_STACK_SIZE 1024*16
#define CROSOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define CROSOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END CROSOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - CROSOS_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23 //Offsets in the GDT table (20 + 3 ring level)
#define USER_CODE_SEGMENT 0x1B //Offsets in the GDT table (offset 18 + 3 ring level)

#define CROSOS_MAX_PROGRAM_ALLOCATIONS 1024
#define CROSOS_MAX_PROCESSES 12

#define CROSOS_MAX_ISR80H_COMMANDS 1024

#define CROSOS_KEYBOARD_BUFFER_SIZE 1024

#endif